name: Run tests
on: [push]
jobs:
  php-tests:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]
        laravel: [8.12.*]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        include:
          - laravel: 8.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:8.12" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest
      - name: Setup App
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          touch database/testdb.sqlite
          php artisan key:generate
          php artisan migrate
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testdb.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
      - name: Compile assets
        run: |
          npm install
          npm run production
      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testdb.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
        run: vendor/bin/phpunit

      - name: Send Slack notification
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}